### ISSUE TITLE
keybinding for C-c C-n  (execute line)

### ISSUE THREAD

**Issue by paynito** [roryk/spacemacs-private#1]
Thank you, copying your setup got polymode working!  

I'm so used to  ⌘-⏎ from R-Studio. 

Do you know how to remap C-c C-n to ⌘-⏎ in polymode/ESS ?

**Comment by roryk** [comment]
Hi @paynito,

haha -- glad this helped someone else. There are some issues using polymode still if you are using evil-mode too, once in a while it will get to a state where pressing 'f' will act like you are in movement mode instead of edit mode.

I'm not sure how to remap the key though.

**Comment by roryk** [comment]
Did you figure out how to do it? I'd love to know. :)

**Comment by roryk** [comment]
Are you using evil-mode in your spacemacs config? I looked at how to remap the key but I think it matters which mode you're using, so I gave up. I can try to figure it out some more this weekend though.

**Comment by paynito** [comment]
Yes, evil-mode!  I still seem to have to switch back to R-Studio to make a pdf. I can only seem to make a .md from my .Rmd with `M-x (ess-swv-knit)`.  i.e. ess-swv-PDF is failing.  Perhaps the .Rmd to .pdf would be a nice keybinding as well for the layer. I have run `C-c C-b` enough today that at least I can compile the whole buffer via muscle memory.

**Comment by roryk** [comment]
Great-- I'm not sure if this will help, but we use the Rmarkdown library (https://cran.r-project.org/web/packages/rmarkdown/) to generate pdf/HTML. I don't use the ess commands though, I just open up the Rmd file in a R buffer and do `library(rmarkdown); render(filename)` with the appropriate header at the top:

```
---
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    highlight: zenburn
    theme: flatly
---
```

**Comment by roryk** [comment]
I know there are pdf options for the rmarkdown library, we tend to make HTML reports though.

**Comment by paynito** [comment]
---
title: "3 groups of 3 box-plots"
author: "my name"
date: "9/2/2016"
output: html_document
#output: pdf_document
---

Thank you, this is what my header looks like.  The .html builds in spacemacs, but if I comment that out and try .pdf I only get a .md.
I will try your commands from the R buffer in spacemacs and see if a pdf pops out somewhere.

**Comment by paynito** [comment]
There must be a way to define these just for polymode instead of globally, but I put them in .spacemacs.  I couldn't get OpenApple-Enter like RStudio.
I bound 3 functions to keys
`<SPC> Enter` evaluates the current R-line.
`<SPC> cb` [un]/comments the selected lines.
`<SPC> stats` turns on poly/Rmd mode for the current buffer.  I define these in .spacemacs under
`(defun dotspacemacs/user-config ()`.   . .

```
(evil-leader/set-key (kbd " cb") 'comment-region)
(evil-leader/set-key (kbd "stats") 'rmd-mode)
(evil-leader/set-key (kbd "RET") 'ess-eval-line-and-step)
```

To find out what the `C-c C-n` that I wanted to rebind was calling, inside a .Rmd file in rmd-mode I hit `<SPC> h d k`   which calls `'describe-key` then `C-c C-n`.  Pretty cool to finally know how to bind keys, should make spacemacs much cooler.
